CONSOLIDATED_NEW = [['CP-RNF-50', 'Bitacora', '/api/bitacora/search?q=test', 'GET', 'APROBADO', '216 x 401'],
 ['CP-RNF-51', 'Bitacora', '/api/bitacora/filter?modulo=&accion=&usuario_id=', 'GET', 'APROBADO', '973 x 400, 216 x 401'],
 ['CP-RNF-52', 'Bitacora', '/api/bitacora/module/{modulo}', 'GET', 'APROBADO', '216 x 401'],
 ['CP-RNF-53', 'Inventario / Stock', '/api/inventory/?sucursal_id=&q=', 'GET', 'APROBADO', '215 x 400, 216 x 401'],
 ['CP-RNF-54', 'Inventario / Stock', '/api/inventory/update-stock', 'PUT', 'APROBADO', '586 x 500, 215 x 400, 216 x 401'],
 ['CP-RNF-55', 'Modulos', '/api/modulos/', 'POST', 'APROBADO', '2,162 x 400, 216 x 401'],
 ['CP-RNF-56', 'Modulos', '/api/modulos/1', 'PUT', 'APROBADO', '2,057 x 400, 216 x 401'],
 ['CP-RNF-57', 'Modulos', '/api/modulos/1', 'DELETE', 'APROBADO', '216 x 401'],
 ['CP-RNF-58', 'Modulos', '/api/modulos/check-unique?field=&value=', 'GET', 'APROBADO', '216 x 401'],
 ['CP-RNF-59', 'Metodos de Pago', '/api/payment-methods/', 'POST', 'APROBADO', '726 x 400, 216 x 401'],
 ['CP-RNF-60', 'Metodos de Pago', '/api/payment-methods/1', 'PUT', 'APROBADO', '387 x 400, 216 x 401'],
 ['CP-RNF-61', 'Metodos de Pago', '/api/payment-methods/1', 'DELETE', 'APROBADO', '216 x 401'],
 ['CP-RNF-62', 'Metodos de Pago', '/api/payment-methods/check-unique?value=', 'GET', 'APROBADO', '216 x 401'],
 ['CP-RNF-63', 'Pagos', '/api/payments/1/approve', 'POST', 'APROBADO', '3 x 500, 216 x 401'],
 ['CP-RNF-64', 'Pagos', '/api/payments/1/reject', 'POST', 'APROBADO', '196 x 500, 1 x 400, 216 x 401'],
 ['CP-RNF-65', 'Perfil', '/api/profile/', 'PUT', 'APROBADO', '785 x 400'],
 ['CP-RNF-66', 'Perfil', '/api/profile/email', 'PUT', 'APROBADO', '216 x 400'],
 ['CP-RNF-67', 'Orden de Compra', '/api/purchase-orders/', 'POST', 'APROBADO', '998 x 400, 432 x 500, 216 x 401'],
 ['CP-RNF-68', 'Orden de Compra', '/api/purchase-orders/1/buy', 'POST', 'APROBADO', '197 x 400, 216 x 401'],
 ['CP-RNF-69', 'QR', '/api/qr/', 'POST', 'APROBADO', '779 x 400, 216 x 401'],
 ['CP-RNF-70', 'QR', '/api/qr/1', 'PUT', 'APROBADO', '779 x 400, 216 x 401'],
 ['CP-RNF-71', 'QR', '/api/qr/1', 'DELETE', 'APROBADO', '216 x 401'],
 ['CP-RNF-72', 'Sucursales', '/api/sucursales/', 'POST', 'APROBADO', '869 x 400, 216 x 401'],
 ['CP-RNF-73', 'Sucursales', '/api/sucursales/1', 'PUT', 'APROBADO', '646 x 400, 216 x 401'],
 ['CP-RNF-74', 'Sucursales', '/api/sucursales/1', 'DELETE', 'APROBADO', '216 x 401'],
 ['CP-RNF-75', 'Sucursales', '/api/sucursales/1/toggle', 'PUT', 'APROBADO', '216 x 401'],
 ['CP-RNF-76', 'Sucursales', '/api/sucursales/check-unique', 'POST', 'APROBADO', '217 x 400, 216 x 401'],
 ['CP-RNF-77', 'Tasas de Cambio', '/api/tasas/', 'POST', 'APROBADO', '216 x 500, 216 x 400, 216 x 401'],
 ['CP-RNF-78', 'Tasas de Cambio', '/api/tasas/1', 'PUT', 'APROBADO', '216 x 500, 216 x 400, 216 x 401'],
 ['CP-RNF-79', 'Tasas de Cambio', '/api/tasas/1', 'DELETE', 'APROBADO', '216 x 401'],
 ['CP-RNF-80', 'Tickets', '/api/tickets/', 'POST', 'APROBADO', '779 x 500, 216 x 400, 216 x 401'],
 ['CP-RNF-81', 'Tickets', '/api/tickets/1/status', 'PUT', 'APROBADO', '197 x 400, 216 x 401'],
 ['CP-RNF-82', 'Tickets', '/api/tickets/1/reply', 'POST', 'APROBADO', '216 x 401'],
 ['CP-RNF-83', 'Bitacora de Vehiculo', '/api/vehicle-log/', 'POST', 'APROBADO', '1,555 x 400, 216 x 500, 216 x 401'],
 ['CP-RNF-84', 'Bitacora de Vehiculo', '/api/vehicle-log/vehicle/{vid}', 'GET', 'APROBADO', '196 x 404, 216 x 401'],
 ['CP-RNF-85', 'Bitacora de Vehiculo', '/api/vehicle-log/client/{cedula}', 'GET', 'APROBADO', '216 x 401'],
 ['CP-RNF-86', 'Bitacora de Vehiculo', '/api/vehicle-log/predictions/1/attend', 'PUT', 'APROBADO', '216 x 401'],
 ['CP-RNF-87', 'Comisiones', '/api/commissions/', 'POST', 'APROBADO', '442 x 500, 216 x 401'],
 ['CP-RNF-88', 'Comisiones', '/api/commissions/1/percentage', 'PUT', 'APROBADO', '216 x 400, 216 x 401'],
 ['CP-RNF-89', 'Pricing / Precios', '/api/pricing/rates/manual', 'POST', 'APROBADO', '216 x 500, 216 x 401'],
 ['CP-RNF-90', 'Pricing / Precios', '/api/pricing/calculate', 'POST', 'APROBADO', '216 x 500, 216 x 401'],
 ['CP-RNF-91', 'Pricing / Precios', '/api/pricing/settings', 'PUT', 'APROBADO', '216 x 500, 216 x 401'],
 ['CP-RNF-92', 'Escaner', '/api/scanner/scan', 'POST', 'APROBADO', '391 x 400, 216 x 401'],
 ['CP-RNF-93', 'Escaner', '/api/scanner/table-qrs', 'POST', 'APROBADO', '432 x 401'],
 ['CP-RNF-94', 'Escaner', '/api/scanner/solicitar-validacion', 'POST', 'APROBADO', '189 x 403, 11 x 404, 216 x 401'],
 ['CP-RNF-95', 'Escaner', '/api/scanner/responder-validacion', 'POST', 'APROBADO', '11 x 404, 216 x 401'],
 ['CP-RNF-96', 'Notificaciones', '/api/notifications/1/read', 'PUT', 'APROBADO', '216 x 401'],
 ['CP-RNF-97', 'Notificaciones', '/api/notifications/1', 'DELETE', 'APROBADO', '216 x 401'],
 ['CP-RNF-98', 'Respaldos', '/api/backup/delete/{filename}', 'DELETE', 'APROBADO', '2 x 404, 216 x 401'],
 ['CP-RNF-99', 'Respaldos', '/api/backup/restore', 'POST', 'APROBADO', '197 x 403, 216 x 401'],
 ['CP-RNF-100', 'Ordenes / Carrito', '/api/orders/cart/add', 'POST', 'APROBADO', '607 x 400, 216 x 401'],
 ['CP-RNF-101', 'Ordenes / Carrito', '/api/orders/cart/1/update', 'PUT', 'APROBADO', '197 x 403, 216 x 401']]

MODULOS_NEW = [{'nombre': 'Bitacora',
  'num': '5.15',
  'pruebas': [{'accion': 'Buscar', 'endpoint': 'GET /api/bitacora/search?q=test', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-50', 'obs': 'No inyectable.', 'params': 'q (query string)'},
              {'accion': 'Filtrar',
               'endpoint': 'GET /api/bitacora/filter?modulo=&accion=&usuario_id=',
               'errores': '973 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-51',
               'obs': 'No inyectable.',
               'params': 'modulo, accion, usuario_id, fecha_inicio, fecha_fin'},
              {'accion': 'Por Modulo',
               'endpoint': 'GET /api/bitacora/module/{modulo}',
               'errores': '216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-52',
               'obs': 'No inyectable.',
               'params': 'modulo en URL'}]},
 {'nombre': 'Inventario / Stock',
  'num': '5.16',
  'pruebas': [{'accion': 'Listar/Buscar',
               'endpoint': 'GET /api/inventory/?sucursal_id=&q=',
               'errores': '215 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-53',
               'obs': 'No inyectable.',
               'params': 'sucursal_id, q, page, per_page'},
              {'accion': 'Actualizar Stock',
               'endpoint': 'PUT /api/inventory/update-stock',
               'errores': '586 x 500, 215 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-54',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'producto_codigo, sucursal_id, stock, stock_minimo'}]},
 {'nombre': 'Modulos',
  'num': '5.17',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/modulos/',
               'errores': '2,162 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-55',
               'obs': 'No inyectable.',
               'params': 'nombre, titulo, descripcion, ruta, icono, grupo, orden, publico, en_sidebar, estado'},
              {'accion': 'Actualizar',
               'endpoint': 'PUT /api/modulos/1',
               'errores': '2,057 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-56',
               'obs': 'No inyectable.',
               'params': 'nombre, titulo, descripcion, ruta, icono, grupo, orden...'},
              {'accion': 'Eliminar', 'endpoint': 'DELETE /api/modulos/1', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-57', 'obs': 'No inyectable.', 'params': 'ID en URL'},
              {'accion': 'Check-Unique',
               'endpoint': 'GET /api/modulos/check-unique?field=&value=',
               'errores': '216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-58',
               'obs': 'No inyectable.',
               'params': 'field, value'}]},
 {'nombre': 'Metodos de Pago',
  'num': '5.18',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/payment-methods/',
               'errores': '726 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-59',
               'obs': 'No inyectable.',
               'params': 'nombre, moneda, datos_pago, permite_credito'},
              {'accion': 'Actualizar',
               'endpoint': 'PUT /api/payment-methods/1',
               'errores': '387 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-60',
               'obs': 'No inyectable.',
               'params': 'nombre, moneda, datos_pago, permite_credito'},
              {'accion': 'Eliminar', 'endpoint': 'DELETE /api/payment-methods/1', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-61', 'obs': 'No inyectable.', 'params': 'ID en URL'},
              {'accion': 'Check-Unique',
               'endpoint': 'GET /api/payment-methods/check-unique?value=',
               'errores': '216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-62',
               'obs': 'No inyectable.',
               'params': 'value'}]},
 {'nombre': 'Pagos',
  'num': '5.19',
  'pruebas': [{'accion': 'Aprobar',
               'endpoint': 'POST /api/payments/1/approve',
               'errores': '3 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-63',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'ID en URL'},
              {'accion': 'Rechazar',
               'endpoint': 'POST /api/payments/1/reject',
               'errores': '196 x 500, 1 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-64',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'observaciones'}]},
 {'nombre': 'Perfil',
  'num': '5.20',
  'pruebas': [{'accion': 'Actualizar Perfil',
               'endpoint': 'PUT /api/profile/',
               'errores': '785 x 400',
               'hora': '05:44',
               'id': 'CP-RNF-65',
               'obs': 'No inyectable.',
               'params': 'nombre, apellido, telefono, direccion'},
              {'accion': 'Cambiar Correo', 'endpoint': 'PUT /api/profile/email', 'errores': '216 x 400', 'hora': '05:44', 'id': 'CP-RNF-66', 'obs': 'No inyectable.', 'params': 'email'}]},
 {'nombre': 'Orden de Compra',
  'num': '5.21',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/purchase-orders/',
               'errores': '998 x 400, 432 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-67',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'proveedor_rif, sucursal_id, producto_codigo, cantidad, precio_unitario, total, observaciones, items'},
              {'accion': 'Comprar',
               'endpoint': 'POST /api/purchase-orders/1/buy',
               'errores': '197 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-68',
               'obs': 'No inyectable.',
               'params': 'observaciones'}]},
 {'nombre': 'QR',
  'num': '5.22',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/qr/',
               'errores': '779 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-69',
               'obs': 'No inyectable.',
               'params': 'tipo, contenido, referencia_id, nota'},
              {'accion': 'Actualizar',
               'endpoint': 'PUT /api/qr/1',
               'errores': '779 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-70',
               'obs': 'No inyectable.',
               'params': 'tipo, contenido, referencia_id, nota'},
              {'accion': 'Eliminar', 'endpoint': 'DELETE /api/qr/1', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-71', 'obs': 'No inyectable.', 'params': 'ID en URL'}]},
 {'nombre': 'Sucursales',
  'num': '5.23',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/sucursales/',
               'errores': '869 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-72',
               'obs': 'No inyectable.',
               'params': 'nombre, direccion, email, telefono'},
              {'accion': 'Actualizar',
               'endpoint': 'PUT /api/sucursales/1',
               'errores': '646 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-73',
               'obs': 'No inyectable.',
               'params': 'nombre, direccion, email, telefono'},
              {'accion': 'Eliminar', 'endpoint': 'DELETE /api/sucursales/1', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-74', 'obs': 'No inyectable.', 'params': 'ID en URL'},
              {'accion': 'Toggle Estado', 'endpoint': 'PUT /api/sucursales/1/toggle', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-75', 'obs': 'No inyectable.', 'params': 'ID en URL'},
              {'accion': 'Check-Unique',
               'endpoint': 'POST /api/sucursales/check-unique',
               'errores': '217 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-76',
               'obs': 'No inyectable.',
               'params': 'field, value'}]},
 {'nombre': 'Tasas de Cambio',
  'num': '5.24',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/tasas/',
               'errores': '216 x 500, 216 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-77',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'monto, fecha, fuente'},
              {'accion': 'Actualizar',
               'endpoint': 'PUT /api/tasas/1',
               'errores': '216 x 500, 216 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-78',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'monto, fecha, fuente'},
              {'accion': 'Eliminar', 'endpoint': 'DELETE /api/tasas/1', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-79', 'obs': 'No inyectable.', 'params': 'ID en URL'}]},
 {'nombre': 'Tickets',
  'num': '5.25',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/tickets/',
               'errores': '779 x 500, 216 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-80',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'cliente_cedula, asunto, descripcion, prioridad, referencia_tipo'},
              {'accion': 'Cambiar Estado', 'endpoint': 'PUT /api/tickets/1/status', 'errores': '197 x 400, 216 x 401', 'hora': '05:44', 'id': 'CP-RNF-81', 'obs': 'No inyectable.', 'params': 'estado'},
              {'accion': 'Responder', 'endpoint': 'POST /api/tickets/1/reply', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-82', 'obs': 'No inyectable.', 'params': 'mensaje'}]},
 {'nombre': 'Bitacora de Vehiculo',
  'num': '5.26',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/vehicle-log/',
               'errores': '1,555 x 400, 216 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-83',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'vehiculo_id, servicio_id, mecanico_cedula, descripcion, kilometraje, orden_venta_id, observaciones, categoria, total'},
              {'accion': 'Por Vehiculo',
               'endpoint': 'GET /api/vehicle-log/vehicle/{vid}',
               'errores': '196 x 404, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-84',
               'obs': 'No inyectable.',
               'params': 'vehiculo en URL'},
              {'accion': 'Por Cliente',
               'endpoint': 'GET /api/vehicle-log/client/{cedula}',
               'errores': '216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-85',
               'obs': 'No inyectable.',
               'params': 'cedula en URL'},
              {'accion': 'Atender Prediccion',
               'endpoint': 'PUT /api/vehicle-log/predictions/1/attend',
               'errores': '216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-86',
               'obs': 'No inyectable.',
               'params': 'ID en URL'}]},
 {'nombre': 'Comisiones',
  'num': '5.27',
  'pruebas': [{'accion': 'Crear',
               'endpoint': 'POST /api/commissions/',
               'errores': '442 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-87',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'mecanico_cedula, porcentaje_comision, precio_servicio, servicio_mecanico_id'},
              {'accion': 'Cambiar Porcentaje',
               'endpoint': 'PUT /api/commissions/1/percentage',
               'errores': '216 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-88',
               'obs': 'No inyectable.',
               'params': 'porcentaje_comision'}]},
 {'nombre': 'Pricing / Precios',
  'num': '5.28',
  'pruebas': [{'accion': 'Tasa Manual',
               'endpoint': 'POST /api/pricing/rates/manual',
               'errores': '216 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-89',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'tipo, monto, fuente'},
              {'accion': 'Calcular',
               'endpoint': 'POST /api/pricing/calculate',
               'errores': '216 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-90',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'precio_usd'},
              {'accion': 'Configuracion',
               'endpoint': 'PUT /api/pricing/settings',
               'errores': '216 x 500, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-91',
               'obs': 'No inyectable. Se observaron errores HTTP 500 (excepcion interna no controlada ante ciertos payloads; robustez a revisar, no es SQLi).',
               'params': 'tasa_referencia_activa, margen_seguridad_pct, banda_variacion_pct, redondeo_bs, hora_congelamiento'}]},
 {'nombre': 'Escaner',
  'num': '5.29',
  'pruebas': [{'accion': 'Escanear', 'endpoint': 'POST /api/scanner/scan', 'errores': '391 x 400, 216 x 401', 'hora': '05:44', 'id': 'CP-RNF-92', 'obs': 'No inyectable.', 'params': 'raw, source'},
              {'accion': 'QRs de Mesa', 'endpoint': 'POST /api/scanner/table-qrs', 'errores': '432 x 401', 'hora': '05:44', 'id': 'CP-RNF-93', 'obs': 'No inyectable.', 'params': 'codigo_mesa, tipo'},
              {'accion': 'Solicitar Validacion',
               'endpoint': 'POST /api/scanner/solicitar-validacion',
               'errores': '189 x 403, 11 x 404, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-94',
               'obs': 'No inyectable.',
               'params': 'orden_id'},
              {'accion': 'Responder Validacion',
               'endpoint': 'POST /api/scanner/responder-validacion',
               'errores': '11 x 404, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-95',
               'obs': 'No inyectable.',
               'params': 'solicitud_id, respuesta'}]},
 {'nombre': 'Notificaciones',
  'num': '5.30',
  'pruebas': [{'accion': 'Marcar Leida', 'endpoint': 'PUT /api/notifications/1/read', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-96', 'obs': 'No inyectable.', 'params': 'ID en URL'},
              {'accion': 'Eliminar', 'endpoint': 'DELETE /api/notifications/1', 'errores': '216 x 401', 'hora': '05:44', 'id': 'CP-RNF-97', 'obs': 'No inyectable.', 'params': 'ID en URL'}]},
 {'nombre': 'Respaldos',
  'num': '5.31',
  'pruebas': [{'accion': 'Eliminar Respaldo',
               'endpoint': 'DELETE /api/backup/delete/{filename}',
               'errores': '2 x 404, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-98',
               'obs': 'No inyectable.',
               'params': 'filename en URL'},
              {'accion': 'Restaurar', 'endpoint': 'POST /api/backup/restore', 'errores': '197 x 403, 216 x 401', 'hora': '05:44', 'id': 'CP-RNF-99', 'obs': 'No inyectable.', 'params': 'filename'}]},
 {'nombre': 'Ordenes / Carrito',
  'num': '5.32',
  'pruebas': [{'accion': 'Agregar al Carrito',
               'endpoint': 'POST /api/orders/cart/add',
               'errores': '607 x 400, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-100',
               'obs': 'No inyectable.',
               'params': 'producto_codigo, cantidad, sucursal_id'},
              {'accion': 'Actualizar Carrito',
               'endpoint': 'PUT /api/orders/cart/1/update',
               'errores': '197 x 403, 216 x 401',
               'hora': '05:44',
               'id': 'CP-RNF-101',
               'obs': 'No inyectable.',
               'params': 'cantidad'}]}]
